# Generated by Django 4.2.7 on 2026-08-11 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_dailyexpense_dailyinterest_delete_expense"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weeklypayment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="borrower",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="borrower",
            name="loan_cycle",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="weeklypayment",
            name="loan_cycle",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="weeklypayment",
            unique_together={("borrower", "payment_date", "loan_cycle")},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionStaffEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_entries",
                        to="core.employee",
                    ),
                ),
                (
                    "finance_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_staff_entries",
                        to="core.financegroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("finance_group", "date", "employee")},
            },
        ),
    ]
