# Generated by Django 4.2.7 on 2026-06-03 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_borrower_date_of_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="date_of_loan",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
