# Generated by Django 4.2.7 on 2026-08-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_weeklypayment_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("started_on", models.DateField(blank=True, null=True)),
                ("closed_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_history",
                        to="core.borrower",
                    ),
                ),
            ],
            options={
                "ordering": ["-closed_on", "-created_at"],
            },
        ),
    ]
