# Generated by Django 4.2.7 on 2026-06-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_borrower_date_of_loan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrower",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="borrower",
            name="date_of_loan",
        ),
    ]
