# Generated by Django 4.2.7 on 2026-06-03 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_borrower_amount_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="borrower",
            name="date_of_loan",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
